### PR TITLE
SDK45

### PR DESCRIPTION
**Pull request by kbrandwijk**
- Ran `expo upgrade` in all projects
- Updated 3 projects using `expo-app-loading` to not use it anymore, as it is now deprecated

Ran a few, didn't run them all. What level of manual checking do we usually do on these after an SDK release?

### CODE REVIEW

**Comment by kbrandwijk** [comment]
Hold on merging, will update all projects to 0.68.2

**Comment by EvanBacon** [comment]
Generally we test the packages that use experimental functionality or features that wouldn't have been otherwise tested during QA. For example, native base is pretty reliable but react-three-fiber (which is more of a web library) may not run as expected.

**Comment by kbrandwijk** [comment]
Decided we can do some additional checks and fixes on the individual basis, but it's worth more to at least have all of the examples on SDK 45 at this point.

**Review by brentvatne — APPROVED** [review]
it's tough to review prs like this which just change deps - but if everything runs then i think it's good!

**Pull request merged**
