### PR TITLE
[moti] Upgrade to Expo SDK 43 and Moti 0.16

### PR DESCRIPTION
**Pull request by byCedric**
Web seems a _little_ bit off, but not sure why. Instead of shrinking + fading away, it grows first (cc @nandorojo). Native does work great.

### CODE REVIEW

**Comment by EvanBacon** [comment]
Is this ready to merge?

**Comment by nandorojo** [comment]
Although it has `~2.2.0` already, and no lock file, so I assume that would resolve to 2.2.4(?)

**Comment by byCedric** [comment]
`react-native-reanimated` only published `2.2.4` under a "stable" tag, not the "latest" flag. So we will still pull in `2.2.3` unfortunately. But as you mentioned, there is no lockfile so once they switch the tag it's in here as well

**Comment by blixit** [comment]
Expo has move it version of react-native from 0.64.2 to 0.64.3: https://github.com/expo/expo/pull/15108

I think you can update your PR accordingly.

**Comment by byCedric** [comment]
@IlyaTaidi Please don't comment on older unrelated PRs. This PR is no longer relevant because it updates the SDK to 43, while we are already at SDK 44.

That being said, it's an issue with `react-native-reanimated@2.3.2`, see https://github.com/software-mansion/react-native-reanimated/issues/3026. You can upgrade to 2.4.1 to avoid it, or wait until a fix is released.

**Pull request closed without merging**
